apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: vsphere-alarm-server
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: vsphere-alarm-server
